# Generated by Django 5.1.4 on 2024-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='due_date',
            new_name='data_prazo',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='title',
            new_name='nome',
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Date')),
                ('tarefas', models.ManyToManyField(blank=True, related_name='dias', to='tarefas.tarefa', verbose_name='Tarefas')),
            ],
        ),
    ]
