# Generated by Django 5.1.4 on 2024-12-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_due_date_tarefa_data_prazo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='tarefas',
        ),
        migrations.AlterField(
            model_name='dia',
            name='data',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.CreateModel(
            name='TarefaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.IntegerField(default=1, verbose_name='Prioridade')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_dia', to='tarefas.dia')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_tarefa', to='tarefas.tarefa')),
            ],
            options={
                'unique_together': {('dia', 'tarefa')},
            },
        ),
    ]
