# Generated by Django 5.1.4 on 2024-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_dia_tarefas_alter_dia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefadia',
            name='tempo_gasto',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo gasto'),
        ),
    ]
