# Generated by Django 5.1.4 on 2024-12-17 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefadia_tempo_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefadia',
            name='tempo_gasto',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Tempo gasto'),
        ),
    ]
