# Generated by Django 5.1.4 on 2024-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_situacao_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.IntegerField(default=1, verbose_name='Prioridade'),
        ),
    ]
