# Generated by Django 5.1.4 on 2024-12-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_tarefa_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='grupo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Grupo'),
        ),
    ]
