# Generated by Django 5.1.4 on 2025-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_remove_tarefa_status_tarefa_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
