# Generated by Django 5.1.7 on 2025-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_turma_movimentacaosaldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255, unique=True)),
                ('quantidade_ic', models.IntegerField()),
                ('expiracao', models.DateTimeField()),
            ],
        ),
    ]
