# Generated by Django 5.1.7 on 2025-03-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tokenic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenic',
            name='valor',
        ),
    ]
