# Generated by Django 5.1.7 on 2025-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_user_matricula_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
