# Generated by Django 5.1.7 on 2025-03-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
