# Generated by Django 5.1.7 on 2025-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_convite_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
