# Generated by Django 5.1.7 on 2025-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_convite_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaosaldo',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
